# -*- coding: utf-8 -*-
"""Reflex-colab-IDE of rx 0.2.0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MXGIlh2m2r9xuq-U7-KFI6zX0PL3rJF
"""

#@title Colab-IDE for reflex: Welcome to Star & Fork
# This colab file is contributed by https://github.com/milochen0418
# Let everyone can open the browser to develop the reflex web app
# in every computer without any installation.
# Welcome to click fork and star this GPLv3 open-source project
# https://github.com/milochen0418/pynecone-colab-ide

#@title Env Variable Setup
# NGROK_KEY: You can sign up at https://ngrok.com/ to get auto token
# OPENAI_KEY: You can sign up and log in to https://platform.openai.com, then open https://platform.openai.com/account/api-keys
import os
os.environ["NGROK_KEY"]  = "Your NGROK_AUTH_TOKEN" #[Necessary] Register your NGROK and set up your auth token here.
os.environ["OPENAI_KEY"] = "Your OPENAI KEY" #[Optional] Register an OpenAI account set the key and be a paid account.
os.environ["COLAB_IDE_VER"] = "rx-0-2-0" # This variable lock the colab-ide environment as reflex==0.2.0.

#@title IDE Clean & Start
from IPython.display import clear_output
import os
!source <(curl -s https://raw.githubusercontent.com/milochen0418/pynecone-colab-ide/main/reflex/setup_base.sh)
clear_output()
!echo "Because IDE Reset, please install reflex environment. If you installed it before, please do it again."

#@title Install  (need 2 ~ 4 minutes)
from IPython.display import clear_output
!source /content/bin/install.sh
clear_output()
!echo "The reflex environment setup is ready. Please get the link to watch your running result."

# Commented out IPython magic to ensure Python compatibility.
#@title Get Link & QRCode
# %run /content/bin/tunnelqr.py

# Commented out IPython magic to ensure Python compatibility.
#@title Terminal
# %reload_ext colabxterm
# %xterm height=300