# -*- coding: utf-8 -*-
"""Reflex-colab-IDE of rx 0.2.0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MXGIlh2m2r9xuq-U7-KFI6zX0PL3rJF
"""

#@title Colab-IDE for reflex: Welcome to Star & Fork
# https://github.com/milochen0418/pynecone-colab-ide
# This colab file is contributed by https://github.com/milochen0418
# Let everyone can open the browser to develop the reflex web app
# in every computer without any installation.
# Welcome to click fork and star this GPLv3 open-source project

#@title Env Variable Setup
# NGROK_KEY: You can sign up at https://ngrok.com/ to get auto token
# OPENAI_KEY: You can sign up and log in to https://platform.openai.com, then open https://platform.openai.com/account/api-keys
import os
os.environ["NGROK_KEY"]  = "Your NGROK_AUTH_TOKEN" #[Necessary] Register your NGROK and set up your auth token here.
os.environ["OPENAI_KEY"] = "Your OPENAI KEY" #[Optional] Register an OpenAI account set the key and be a paid account.
os.environ["COLAB_IDE_VER"] = "rx-0-2-0" # This variable lock the colab-ide environment as reflex==0.2.0.
# [Optinal] GitHub setting.
os.environ["GH_TOKEN"] = "Your GITHUB TOKEN"  # Refer this link to get https://dev.to/shafia/support-for-password-authentication-was-removed-please-use-a-personal-access-token-instead-4nbk
os.environ["GH_EMAIL"] = "Your email" # I set the email that sign up for my github account.
os.environ["GH_NAME"] = "You name" # I set milochen0418 because my github is in https://github.com/milochen0418
!git config --global user.email "$GH_EMAIL"
!git config --global user.name "$GH_NAME"
# You can clone project by the following command.
# git clone https://$GITHUB_TOKEN@github.com/milochen0418/reflex-community-examples.git

#@title IDE Clean & Start
from IPython.display import clear_output
import os
!source <(curl -s https://raw.githubusercontent.com/milochen0418/pynecone-colab-ide/main/reflex/setup_base.sh)
clear_output()
!echo "Because IDE Reset, please install reflex environment. If you installed it before, please do it again."

#@title Install  (need 2 ~ 4 minutes)
from IPython.display import clear_output
!source /content/bin/install.sh
clear_output()
!echo "The reflex environment setup is ready. Please get the link to watch your running result."

# Commented out IPython magic to ensure Python compatibility.
#@title Get Link & QRCode
# %run /content/bin/tunnelqr.py

# Commented out IPython magic to ensure Python compatibility.
#@title Terminal
# %reload_ext colabxterm
# %xterm height=300

"""# Q & A
- Q1: Why the webapp in colab-ide is very slow? Is it the issue of reflex framework?
- A1: The answer is NO. The reflex framework is not slow. The slow speed is because we use ngrok tunnel to map the localhost of colab instance to the public domain name. This [YouTube video](https://www.youtube.com/watch?v=OgXTFoAlNoQ) proves it.
-----
- Q2: When I run the cell `Get Link & QRCode`, it is failed. But I have set
 the correct NGROK_KEY.
- A2: When you use free ngrok, It only supports one machine. You may create another instance from another colab. In the colab, you can open `Manage session` and terminal all the running instance to ensure no other machine use this Ngrok key a.k.a auth token.  
"""